-- Create a table for storing leads if it doesn't exist
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  person_name text not null,
  company_name text not null,
  email text not null,
  phone text not null,
  instagram text,
  revenue text not null,
  budget text not null
);

-- Enable Row Level Security (RLS)
alter table public.leads enable row level security;

-- Drop the policy if it exists to avoid errors when recreating
drop policy if exists "Enable insert for everyone" on public.leads;

-- Create a policy to allow anyone to insert leads
create policy "Enable insert for everyone" on public.leads
  for insert
  with check (true);
